name = "transmoda-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Environment variables
# You need to set these using: wrangler secret put <VARIABLE_NAME>
# Or add them to your .env file for local development
# 
# Required secrets:
# - GEMINI_API_KEY: Your Google Gemini API key
# - PROMPT_SUMMARY: AI prompt for document summarization
# - PROMPT_SHORTFORM: AI prompt for shortform content generation

# Durable Objects
[[durable_objects.bindings]]
name = "TRANS_SESSION"
class_name = "TransSession"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["TransSession"]

[env.production]
name = "transmoda-worker-prod"

# Example: restrict CORS to known frontends in production (set via env/secrets)
# vars = { ALLOWED_ORIGINS = "https://transmoda.app,https://www.transmoda.app" }

# Durable Objects for production
[[env.production.durable_objects.bindings]]
name = "TRANS_SESSION"
class_name = "TransSession"

# Migrations for Durable Objects in production
[[env.production.migrations]]
tag = "v1"
new_classes = ["TransSession"]

# Uncomment when R2 is enabled
# [[r2_buckets]]
# binding = "PDF_BUCKET"
# bucket_name = "transmoda-pdfs"
