name = "transmoda-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["formdata_parser_supports_files"]

# Environment variables
# You need to set these using: wrangler secret put <VARIABLE_NAME>
# Or add them to your .env file for local development
# 
# Required secrets:
# - GEMINI_API_KEY: Your Google Gemini API key
# - PROMPT_SUMMARY: AI prompt for document summarization
# - PROMPT_SHORTFORM: AI prompt for shortform content generation
#
# Example prompts:
# PROMPT_SUMMARY: "Summarize the document in ONE concise paragraph (3-5 sentences) in GitHub-Flavored Markdown. No bullets, no headings, no citations like [1]."
# PROMPT_SHORTFORM: "Create 5 viral shortform content ideas from this document for TikTok, Instagram Reels, and YouTube Shorts. Each idea should have a compelling title, engaging voiceover script, and relevant hashtags. Use the format: *Title: [title] *Voiceover: [script] *Hashtags: [tags] separated by ***"

# Durable Objects
[[durable_objects.bindings]]
name = "TRANS_SESSION"
class_name = "TransSession"

# Migrations for Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["TransSession"]

[env.production]
name = "transmoda-worker-prod"

# Example: restrict CORS to known frontends in production (set via env/secrets)
# vars = { ALLOWED_ORIGINS = "https://transmoda.app,https://www.transmoda.app" }

# Durable Objects for production
[[env.production.durable_objects.bindings]]
name = "TRANS_SESSION"
class_name = "TransSession"

# Migrations for Durable Objects in production
[[env.production.migrations]]
tag = "v1"
new_classes = ["TransSession"]

# Uncomment when R2 is enabled
# [[r2_buckets]]
# binding = "PDF_BUCKET"
# bucket_name = "transmoda-pdfs"
